### ISSUE TITLE
wav file after dereverberator using WPE algorithm

### ISSUE THREAD

**Issue by yuan9778** [kkumatani/distant_speech_recognition#5]
Dear Kenichi,
I run Single channel WPE dereverberator using the following script:
`python test_subband_dereverberator.py -i data/CMU/R1/M1005/KINECT/RAW/segmented/U1001_1M_16k_b16_c1.wav -o out/U1001_1M_16k_b16_c1.wav`

I listened to the generated wav file and the original one, and I can't tell the difference. They sound the same. Is it normal?

Thanks,
Sanqing

**Comment by kkumatani** [comment]
The WPE is "moderate" linear processing. It would rather avoid no-linear distortion in order to maintain 
 speech recognition accuracy. Also, the example is done on the real data. So, you may not hear a significant difference. You can synthesize a test by convolving clean data with a room impulse response linearly. Then, you can quantize the quality with traditional signal processing criteria like DRR.

**Comment by yuan9778** [comment]
Thanks much for your reply!
